### PR TITLE
Fast scroller

### LINKED ISSUE #233: Add fast scrolling again
You switched layout of issue content to fast scrolling some time ago. It is not working anymore. Any reason why? If has long content you need to scroll a long time.

### PR DESCRIPTION
**Pull request by Tunous**
Closes #233.

### CODE REVIEW

File: src/com/gh4a/fragment/LoadingListFragmentBase.java [hunk 1]
```diff
@@ -54,6 +57,13 @@ protected View onCreateContentView(LayoutInflater inflater, ViewGroup parent) {
                     UiUtils.resolveDrawable(getActivity(), R.attr.listBackground));
         }
 
+        mFastScroller = (RecyclerFastScroller) view.findViewById(R.id.fast_scroller);
+        mFastScroller.attachRecyclerView(mRecyclerView);
+
+        int color = UiUtils.resolveColor(view.getContext(), R.attr.colorControlNormal);
+        color = Color.argb(93, Color.red(color), Color.green(color), Color.blue(color));
```
Comment (maniac103) [inline src/com/gh4a/fragment/LoadingListFragmentBase.java]: Is there a specific reason not to use an XML defined color here? I think I'd prefer that.

File: res/layout/generic_list.xml [hunk 2]
```diff
@@ -1,7 +1,21 @@
...
+    <com.gh4a.widget.ContextMenuAwareRecyclerView
+        android:id="@+id/list"
+        android:layout_width="match_parent"
+        android:layout_height="match_parent" />
+
+    <com.pluscubed.recyclerfastscroll.RecyclerFastScroller
+        android:id="@+id/fast_scroller"
+        android:layout_width="wrap_content"
+        android:layout_height="match_parent"
+        android:layout_gravity="end"
```
Comment (maniac103) [inline res/layout/generic_list.xml]: right or right|end

(min API is < 17 and we don't have RTL language translations anyway)

File: src/com/gh4a/fragment/LoadingListFragmentBase.java (hunk 1 above)
Comment (Tunous) [inline src/com/gh4a/fragment/LoadingListFragmentBase.java]: Changed. I did it like this because I tried to replicate what *(I think)* happens with original scrollbar thumb where there is a tint of another color that changes transparency. But you are right. Setting a color in a regular way is better ;)

File: res/layout/generic_list.xml (hunk 2 above)
Comment (Tunous) [inline res/layout/generic_list.xml]: Fixed.
