### PR TITLE
Fix toolbar collapsing when there are no items

### LINKED ISSUE #410: If there are no issues in issue list view header can't be scrolled to expand

### PR DESCRIPTION
**Pull request by Tunous**
Closes #410.

### CODE REVIEW

File: src/com/gh4a/fragment/LoadingListFragmentBase.java [hunk 1]
```diff
@@ -84,6 +87,7 @@ protected void updateEmptyState() {
 
         mRecyclerView.setVisibility(empty ? View.GONE : View.VISIBLE);
         mEmptyView.setVisibility(empty ? View.VISIBLE : View.GONE);
```
Comment (maniac103) [inline src/com/gh4a/fragment/LoadingListFragmentBase.java]: Can probably keep this view permanently visible now.
