### PR TITLE
Fix crash when a PR review is made by a deleted user

### LINKED ISSUE #1082: Crash while displaying a PR review made by a deleted user
The app crashes consistently after scrolling a bit through [this PR](https://github.com/ElderDrivers/EdXposed/pull/870), the stack trace makes me think that the crash is caused by a review made by a deleted user on that PR.
```
FATAL EXCEPTION: main
Process: com.gh4a, PID: 23163
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.meisolsson.githubsdk.model.User.login()' on a null object reference
	at com.gh4a.adapter.timeline.ReviewViewHolder.formatTitle(ReviewViewHolder.java:238)
	at com.gh4a.adapter.timeline.ReviewViewHolder.bind(ReviewViewHolder.java:117)
	at com.gh4a.adapter.timeline.ReviewViewHolder.bind(ReviewViewHolder.java:38)
	at com.gh4a.adapter.timeline.TimelineItemAdapter.onBindViewHolder(TimelineItemAdapter.java:272)
	at com.gh4a.adapter.timeline.TimelineItemAdapter.onBindViewHolder(TimelineItemAdapter.java:30)
	at com.gh4a.adapter.RootAdapter.onBindViewHolder(RootAdapter.java:234)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```

### PR DESCRIPTION
**Pull request by Fs00**
Apparently, in this specific case GitHub API returns a null user instead of "ghost" as it usually does.

Fixes #1082

### CODE REVIEW

File: app/src/main/java/com/gh4a/adapter/timeline/ReviewViewHolder.java [hunk 1]
```diff
@@ -235,7 +235,10 @@ private void formatTitle(final Review review) {
                 break;
         }
 
-        String login = review.user().login();
+        User reviewer = review.user();
+        // In this case, GitHub API returns a null user (instead of the "ghost" user) when
+        // the review author is a deleted user
+        String login = reviewer != null ? reviewer.login() : "ghost";
```
Comment (maniac103) [inline app/src/main/java/com/gh4a/adapter/timeline/ReviewViewHolder.java:241]: I think using `ApiHelpers.getUserLogin()` would be more appropriate.

Comment (Fs00) [reply app/src/main/java/com/gh4a/adapter/timeline/ReviewViewHolder.java]: Done, thanks! I wasn't aware of that method
